def settings():
  global X_MES, Y_MES, X_PROMPT, Y_PROMPT, INITIALWRITE, SECONDWRITE, WAITINGTIME
  INITIALWRITE = 10
  SECONDWRITE = 5
  WAITINGTIME = 200
  X_MES = 0
  Y_MES = 0
  X_PROMPT = 0
  Y_PROMPT = 0